In [1]:
import numpy as np

In [2]:
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(np.matmul(matrix1,matrix2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
