In [15]:
import numpy as np

In [16]:
l1=[i for i in range(1,11,3)]
l2=[list([i,i+1,i+2]) for i in l1]
l3=[i for i in range(11,21,3)]
l4=[list([i,i+1,i+2]) for i in l3]
l5=[l2]+[l4]

In [17]:
threeDarray=np.array(l5)
print(threeDarray)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]
  [20 21 22]]]


In [18]:
print(threeDarray.transpose())

[[[ 1 11]
  [ 4 14]
  [ 7 17]
  [10 20]]

 [[ 2 12]
  [ 5 15]
  [ 8 18]
  [11 21]]

 [[ 3 13]
  [ 6 16]
  [ 9 19]
  [12 22]]]


In [19]:
print(threeDarray.T)

[[[ 1 11]
  [ 4 14]
  [ 7 17]
  [10 20]]

 [[ 2 12]
  [ 5 15]
  [ 8 18]
  [11 21]]

 [[ 3 13]
  [ 6 16]
  [ 9 19]
  [12 22]]]
