In [10]:
import numpy as np

In [11]:
l1=[i for i in range(1,11,3)]
l2=[list([i,i+1,i+2]) for i in l1]

In [12]:
twoDArray=np.array(l2)

In [13]:
print(twoDArray)
print("Number of Dimension : ",twoDArray.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Number of Dimension :  2


In [14]:
print(twoDArray[1][0])

4
