In [10]:
import numpy as np

In [11]:
l1=[i for i in range(1,11,3)]
l2=[list([i,i+1,i+2]) for i in l1]
l3=[i for i in range(11,21,3)]
l4=[list([i,i+1,i+2]) for i in l3]
l5=[l2]+[l4]

In [12]:
oneDarray=np.array(l1)
twoDarray=np.array(l2)
threeDarray=np.array(l5)

In [13]:
print("One D Array : ",oneDarray)
print("Two D Array : ",twoDarray)
print("Three D Array : ",threeDarray)

One D Array :  [ 1  4  7 10]
Two D Array :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Three D Array :  [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]
  [20 21 22]]]


In [14]:
print(oneDarray.shape)
print(twoDarray.shape)
print(threeDarray.shape)

(4,)
(4, 3)
(2, 4, 3)
